version: "3"

services:
  otd:
    image: ${APP_IMAGE:-ghcr.io/wojciechpolak/on-this-day:latest}
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ICS_URLS
      - APP_PORT=8080
      - APP_CACHE_TTL
