version: '3'

services:
  otd:
    image: ${APP_IMAGE:-ghcr.io/wojciechpolak/on-this-day:latest}
    restart: unless-stopped
    build: .
    ports:
      - '8080:8080'
    environment:
      PORT: '8080'
      NUXT_APP_ICS_URLS: ${APP_ICS_URLS}
      NUXT_APP_CACHE_TTL: ${APP_CACHE_TTL:-86400}
      NUXT_APP_WIKIPEDIA_LANG_ENFORCE: ${APP_WIKIPEDIA_LANG_ENFORCE:-}
      NUXT_APP_WIKIPEDIA_LANG: ${APP_WIKIPEDIA_LANG:-en}
      NUXT_APP_WIKIPEDIA_SECTIONS: ${APP_WIKIPEDIA_SECTIONS:-}
